#!/bin/bash
shopt -s globstar

if [ -n "${PHP_GID}" ]; then
    groupmod --gid "${PHP_GID}" --non-unique www-data
fi

if [ -n "${PHP_UID}" ]; then
    usermod --non-unique --uid "${PHP_UID}" www-data
fi

mkdir -p /run/php

if [ -f /usr/local/etc/php/php.ini ]; then
    dockerize -delims '⁅⁅:⁆⁆' -template /usr/local/etc/php/php.ini:/usr/local/etc/php/php.ini
fi
for FILE in /usr/local/etc/php/conf.d/*; do
    dockerize -delims '⁅⁅:⁆⁆' -template "${FILE}":"${FILE}"
done
for FILE in /usr/local/etc/php-fpm.d/*; do
    dockerize -delims '⁅⁅:⁆⁆' -template "${FILE}":"${FILE}"
done
